### PR TITLE
remove auth token  section from pan, digi, esign

### PR DESCRIPTION
**Pull request by oreanroy**
removed section which talks about generating auth token.

### CODE REVIEW

**Comment by oreanroy** [comment]
Not be merged as of now.

**Comment by aditya-67** [comment]
@oreanroy 
Why only PAN, Digilocker, and eSign? Should we remove it from all the DG blocks that have this `Auth Token` API?

**Comment by oreanroy** [comment]
@aditya-67  The auth api is common to all dg-blocks agnostic to the block.  In documentation just PAN, Digilocker, and design mentions it. So removing from these removes from all block.

**Review by shrivatsas — APPROVED** [review]

**Comment by aditya-67** [comment]
@oreanroy As I'm seeing, Aadhaar KYC, BAV also have them. Can you please check?

OKYC - https://docs.setu.co/data/okyc/api-reference#/category~Auth/operation~GetAuthtoken
BAV - https://docs.setu.co/data/bav/penny-drop/api-reference#/category~Misc/operation~GetAuthtoken

**Pull request merged**
